#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := m5-rotor

include $(IDF_PATH)/make/project.mk

EXTRA_CXXFLAGS="-Wno-error=reorder"
